// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // AdvertisePosition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class AdvertisePosition
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 广告位编码
        ///</summary>
        public string Code { get; set; } // Code (length: 128)

        ///<summary>
        /// 1：盖付通 2：盖掌柜
        ///</summary>
        public int? AppId { get; set; } // AppID

        ///<summary>
        /// 广告位名称
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 广告位内容
        ///</summary>
        public string Content { get; set; } // Content

        ///<summary>
        /// 1、单个图片 2、幻灯片 3、文字
        ///</summary>
        public int? Type { get; set; } // Type

        ///<summary>
        /// 0：禁用 1：启用
        ///</summary>
        public int? Status { get; set; } // Status
        public int? Width { get; set; } // Width

        ///<summary>
        /// 高
        ///</summary>
        public int? Height { get; set; } // Height

        ///<summary>
        /// 点击量
        ///</summary>
        public int? Clicks { get; set; } // Clicks
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public AdvertisePosition()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
