// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // BASE_AdminUser
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BaseAdminUserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BaseAdminUser>
    {
        public BaseAdminUserConfiguration()
            : this("dbo")
        {
        }

        public BaseAdminUserConfiguration(string schema)
        {
            ToTable("BASE_AdminUser", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SystemId).HasColumnName(@"SystemId").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Salt).HasColumnName(@"Salt").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.Locked).HasColumnName(@"Locked").HasColumnType("bit").IsRequired();
            Property(x => x.LastLoginDate).HasColumnName(@"LastLoginDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.Remark1).HasColumnName(@"Remark1").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Remark2).HasColumnName(@"Remark2").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Remark3).HasColumnName(@"Remark3").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Remark4).HasColumnName(@"Remark4").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Remark5).HasColumnName(@"Remark5").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.IsDisabled).HasColumnName(@"IsDisabled").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
