// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // BASE_ELMAH_Error
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BaseElmahError
    {

        ///<summary>
        /// 主键
        ///</summary>
        public System.Guid ErrorId { get; set; } // ErrorId (Primary key)

        ///<summary>
        /// 程序名称
        ///</summary>
        public string Application { get; set; } // Application (length: 60)

        ///<summary>
        /// 主机名
        ///</summary>
        public string Host { get; set; } // Host (length: 50)

        ///<summary>
        /// 类型
        ///</summary>
        public string Type { get; set; } // Type (length: 100)

        ///<summary>
        /// 来源
        ///</summary>
        public string Source { get; set; } // Source (length: 60)

        ///<summary>
        /// 消息
        ///</summary>
        public string Message { get; set; } // Message (length: 500)

        ///<summary>
        /// 用户
        ///</summary>
        public string User { get; set; } // User (length: 50)

        ///<summary>
        /// 状态码
        ///</summary>
        public int StatusCode { get; set; } // StatusCode

        ///<summary>
        /// UTC时间
        ///</summary>
        public System.DateTime TimeUtc { get; set; } // TimeUtc

        ///<summary>
        /// 序列
        ///</summary>
        public int Sequence { get; set; } // Sequence

        ///<summary>
        /// XML内容
        ///</summary>
        public string AllXml { get; set; } // AllXml (length: 1073741823)
    }

}
// </auto-generated>
