// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // BASE_Role
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BaseRole
    {

        ///<summary>
        /// 自增ID
        ///</summary>
        public long Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 系统ID
        ///</summary>
        public string SystemId { get; set; } // SystemId (length: 50)

        ///<summary>
        /// 角色ID
        ///</summary>
        public string RoleId { get; set; } // RoleId (length: 50)

        ///<summary>
        /// 角色名称
        ///</summary>
        public string RoleName { get; set; } // RoleName (length: 50)

        ///<summary>
        /// 角色类型
        ///</summary>
        public string RoleType { get; set; } // RoleType (length: 50)

        ///<summary>
        /// 描述
        ///</summary>
        public string Description { get; set; } // Description (length: 255)

        ///<summary>
        /// 备注
        ///</summary>
        public string Remark { get; set; } // Remark (length: 500)

        ///<summary>
        /// 添加者
        ///</summary>
        public string CreateBy { get; set; } // CreateBy (length: 50)

        ///<summary>
        /// 添加时间
        ///</summary>
        public System.DateTime? CreateDate { get; set; } // CreateDate

        ///<summary>
        /// 更新者
        ///</summary>
        public string UpdateBy { get; set; } // UpdateBy (length: 50)

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateDate { get; set; } // UpdateDate

        ///<summary>
        /// 是否失效
        ///</summary>
        public bool IsDisabled { get; set; } // IsDisabled

        public BaseRole()
        {
            IsDisabled = false;
        }
    }

}
// </auto-generated>
