// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // BASE_ELMAH_Error
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BaseElmahErrorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BaseElmahError>
    {
        public BaseElmahErrorConfiguration()
            : this("dbo")
        {
        }

        public BaseElmahErrorConfiguration(string schema)
        {
            ToTable("BASE_ELMAH_Error", schema);
            HasKey(x => x.ErrorId);

            Property(x => x.ErrorId).HasColumnName(@"ErrorId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Application).HasColumnName(@"Application").HasColumnType("nvarchar").IsRequired().HasMaxLength(60);
            Property(x => x.Host).HasColumnName(@"Host").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Source).HasColumnName(@"Source").HasColumnType("nvarchar").IsRequired().HasMaxLength(60);
            Property(x => x.Message).HasColumnName(@"Message").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.User).HasColumnName(@"User").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.StatusCode).HasColumnName(@"StatusCode").HasColumnType("int").IsRequired();
            Property(x => x.TimeUtc).HasColumnName(@"TimeUtc").HasColumnType("datetime").IsRequired();
            Property(x => x.Sequence).HasColumnName(@"Sequence").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AllXml).HasColumnName(@"AllXml").HasColumnType("ntext").IsRequired().IsMaxLength();
        }
    }

}
// </auto-generated>
