// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // BASE_UserPreferenceConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BaseUserPreferenceConfig
    {
        public long Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 系统名称
        ///</summary>
        public string Application { get; set; } // Application (length: 100)
        public string UserId { get; set; } // UserId (length: 50)
        public string Key { get; set; } // Key (length: 50)
        public string Value { get; set; } // Value (length: 50)
        public string Category { get; set; } // Category (length: 50)
        public string Description { get; set; } // Description (length: 100)
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public string CreateBy { get; set; } // CreateBy (length: 50)
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public string UpdateBy { get; set; } // UpdateBy (length: 50)
        public bool IsDisabled { get; set; } // IsDisabled
    }

}
// </auto-generated>
