// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // BusinessCategory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BusinessCategory
    {

        ///<summary>
        /// 唯一主键ID
        ///</summary>
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// ID,自增长
        ///</summary>
        public long Id { get; set; } // ID

        ///<summary>
        /// 编码
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 分类名称
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 前端样式
        ///</summary>
        public string Style { get; set; } // Style (length: 4000)

        ///<summary>
        /// 排序
        ///</summary>
        public int? Sort { get; set; } // Sort

        ///<summary>
        /// 创建时间
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 最小服务费率
        ///</summary>
        public int? MinServiceFee { get; set; } // MinServiceFee

        ///<summary>
        /// 最大服务费率
        ///</summary>
        public int? MaxServiceFee { get; set; } // MaxServiceFee

        ///<summary>
        /// 父级ID
        ///</summary>
        public long? ParentId { get; set; } // ParentID

        ///<summary>
        /// 状态：0删除，1正常
        ///</summary>
        public int? Status { get; set; } // Status

        public BusinessCategory()
        {
            Sort = 1;
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
