// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // DictionaryConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class DictionaryConfigConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DictionaryConfig>
    {
        public DictionaryConfigConfiguration()
            : this("dbo")
        {
        }

        public DictionaryConfigConfiguration(string schema)
        {
            ToTable("DictionaryConfig", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SystemId).HasColumnName(@"SystemId").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("bigint").IsRequired();
            Property(x => x.ParentCode).HasColumnName(@"ParentCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Value1).HasColumnName(@"Value1").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Value2).HasColumnName(@"Value2").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Order).HasColumnName(@"Order").HasColumnType("int").IsRequired();
            Property(x => x.Path).HasColumnName(@"Path").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("int").IsRequired();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("bit").IsRequired();
            Property(x => x.CreateBy).HasColumnName(@"CreateBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.UpdateBy).HasColumnName(@"UpdateBy").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime2").IsOptional();
            Property(x => x.IsDisabled).HasColumnName(@"IsDisabled").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
