// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // DictionaryConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class DictionaryConfig
    {

        ///<summary>
        /// 主键
        ///</summary>
        public long Id { get; set; } // Id (Primary key)

        ///<summary>
        /// 系统ID
        ///</summary>
        public string SystemId { get; set; } // SystemId (length: 50)

        ///<summary>
        /// 父级ID
        ///</summary>
        public long ParentId { get; set; } // ParentId

        ///<summary>
        /// 父级编码
        ///</summary>
        public string ParentCode { get; set; } // ParentCode (length: 50)

        ///<summary>
        /// 编码
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 名称
        ///</summary>
        public string Name { get; set; } // Name (length: 50)

        ///<summary>
        /// 值1
        ///</summary>
        public string Value1 { get; set; } // Value1 (length: 255)

        ///<summary>
        /// 值2
        ///</summary>
        public string Value2 { get; set; } // Value2 (length: 255)

        ///<summary>
        /// 排序
        ///</summary>
        public int Order { get; set; } // Order

        ///<summary>
        /// 路径
        ///</summary>
        public string Path { get; set; } // Path (length: 2000)

        ///<summary>
        /// 类型
        ///</summary>
        public int Type { get; set; } // Type

        ///<summary>
        /// 状态 0正常 1禁用
        ///</summary>
        public bool Status { get; set; } // Status

        ///<summary>
        /// 添加者
        ///</summary>
        public string CreateBy { get; set; } // CreateBy (length: 50)

        ///<summary>
        /// 添加时间
        ///</summary>
        public System.DateTime? CreateDate { get; set; } // CreateDate

        ///<summary>
        /// 更新者
        ///</summary>
        public string UpdateBy { get; set; } // UpdateBy (length: 50)

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateDate { get; set; } // UpdateDate

        ///<summary>
        /// 是否失效 0否 1是
        ///</summary>
        public bool IsDisabled { get; set; } // IsDisabled

        public DictionaryConfig()
        {
            Status = false;
            CreateDate = System.DateTime.UtcNow;
            UpdateDate = System.DateTime.UtcNow;
            IsDisabled = false;
        }
    }

}
// </auto-generated>
