// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class GetServiceCodeByCodeReturnModel
    {
        public System.DateTime? CreateTime { get; set; }
        public System.String MerchantCode { get; set; }
        public System.String OwnerCode { get; set; }
        public System.String Code { get; set; }
        public System.String OperationName { get; set; }
        public System.Boolean? IsBind { get; set; }
        public System.Int32? Type { get; set; }
        public System.DateTime? SalesTime { get; set; }
    }

}
// </auto-generated>
