// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // GXSLineInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class GxsLineInfo
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 货道编码
        ///</summary>
        public string Code { get; set; } // Code (length: 128)

        ///<summary>
        /// 租用商家IDID
        ///</summary>
        public System.Guid? RenterUniqueId { get; set; } // RenterUniqueID

        ///<summary>
        /// 机器ID
        ///</summary>
        public System.Guid? MachineUniqueId { get; set; } // MachineUniqueID

        ///<summary>
        /// 货道名
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 状态
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 租用失效时间
        ///</summary>
        public System.DateTime? ExpireTime { get; set; } // ExpireTime
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 商家盖网号
        ///</summary>
        public string MerchantCode { get; set; } // MerchantCode (length: 50)

        public GxsLineInfo()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
