// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // GXSMachine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class GxsMachineConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GxsMachine>
    {
        public GxsMachineConfiguration()
            : this("dbo")
        {
        }

        public GxsMachineConfiguration(string schema)
        {
            ToTable("GXSMachine", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Logo).HasColumnName(@"Logo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.ContactMobile).HasColumnName(@"ContactMobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.MerchantUniqueId).HasColumnName(@"MerchantUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.BusinessCategoryId).HasColumnName(@"BusinessCategoryID").HasColumnType("int").IsOptional();
            Property(x => x.ActivationCode).HasColumnName(@"ActivationCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.IsActivated).HasColumnName(@"IsActivated").HasColumnType("bit").IsOptional();
            Property(x => x.Currency).HasColumnName(@"Currency").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.Country).HasColumnName(@"Country").HasColumnType("int").IsOptional();
            Property(x => x.CountryName).HasColumnName(@"CountryName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("int").IsOptional();
            Property(x => x.ProvinceName).HasColumnName(@"ProvinceName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("int").IsOptional();
            Property(x => x.CityName).HasColumnName(@"CityName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.District).HasColumnName(@"District").HasColumnType("int").IsOptional();
            Property(x => x.DistrictName).HasColumnName(@"DistrictName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsOptional().HasMaxLength(225);
            Property(x => x.OperatorUniqueId).HasColumnName(@"OperatorUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.OperatorIp).HasColumnName(@"OperatorIP").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MerchantCode).HasColumnName(@"MerchantCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SetupTime).HasColumnName(@"SetupTime").HasColumnType("datetime").IsOptional();
            Property(x => x.Remark).HasColumnName(@"Remark").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.PrivateKey).HasColumnName(@"PrivateKey").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.PublicKey).HasColumnName(@"PublicKey").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DeviceId).HasColumnName(@"DeviceID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("float").IsOptional();
            Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("float").IsOptional();
            Property(x => x.IsRecommend).HasColumnName(@"IsRecommend").HasColumnType("bit").IsOptional();
            Property(x => x.ErrorCode).HasColumnName(@"ErrorCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Version).HasColumnName(@"Version").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(12);
            Property(x => x.LastConnectTime).HasColumnName(@"LastConnectTime").HasColumnType("datetime").IsOptional();
            Property(x => x.ConnectStatus).HasColumnName(@"ConnectStatus").HasColumnType("int").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.StoreUniqueId).HasColumnName(@"StoreUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.KeyWords).HasColumnName(@"KeyWords").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
        }
    }

}
// </auto-generated>
