// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // GXSProduct
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class GxsProduct
    {
        public long Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 商品ID
        ///</summary>
        public System.Guid? ProductUniqueId { get; set; } // ProductUniqueID

        ///<summary>
        /// 商品名称
        ///</summary>
        public string ProductName { get; set; } // ProductName (length: 500)

        ///<summary>
        /// 机器ID
        ///</summary>
        public System.Guid? MachineUniqueId { get; set; } // MachineUniqueID

        ///<summary>
        /// 货道ID
        ///</summary>
        public int? LineId { get; set; } // LineID

        ///<summary>
        /// 货道编码
        ///</summary>
        public string LineCode { get; set; } // LineCode (length: 32)

        ///<summary>
        /// 状态
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 店铺分类ID
        ///</summary>
        public long? StoreCategoryId { get; set; } // StoreCategoryID

        ///<summary>
        /// 店铺分类名称
        ///</summary>
        public string StoreCategoryName { get; set; } // StoreCategoryName (length: 200)
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpateTime { get; set; } // UpateTime

        ///<summary>
        /// 商品条形码
        ///</summary>
        public string Barcode { get; set; } // Barcode (length: 50)

        public GxsProduct()
        {
            CreateTime = System.DateTime.UtcNow;
            UpateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
