// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // MerchantApplication
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class MerchantApplicationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MerchantApplication>
    {
        public MerchantApplicationConfiguration()
            : this("dbo")
        {
        }

        public MerchantApplicationConfiguration(string schema)
        {
            ToTable("MerchantApplication", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.Portrait).HasColumnName(@"Portrait").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.UserCode).HasColumnName(@"UserCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ReferralCode).HasColumnName(@"ReferralCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.RealName).HasColumnName(@"RealName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.IdCardNo).HasColumnName(@"IDCardNO").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(18);
            Property(x => x.IdCardValidTime).HasColumnName(@"IDCardValidTime").HasColumnType("datetime").IsOptional();
            Property(x => x.IdCardFrontImg).HasColumnName(@"IDCardFrontImg").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.IdCardBackImg).HasColumnName(@"IDCardBackImg").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.SalesOutletName).HasColumnName(@"SalesOutletName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.SpecialIndustry).HasColumnName(@"SpecialIndustry").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.IdCardOfBindBank).HasColumnName(@"IDCardOfBindBank").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(18);
            Property(x => x.IdCardFrontImgOfBindBank).HasColumnName(@"IDCardFrontImgOfBindBank").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.IdCardBackImgOfBindBank).HasColumnName(@"IDCardBackImgOfBindBank").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.IdCardExpDateOfBindBank).HasColumnName(@"IDCardExpDateOfBindBank").HasColumnType("datetime").IsOptional();
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("int").IsOptional();
            Property(x => x.City).HasColumnName(@"City").HasColumnType("int").IsOptional();
            Property(x => x.District).HasColumnName(@"District").HasColumnType("int").IsOptional();
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.LicenseImg).HasColumnName(@"LicenseImg").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.LicenseExpirationDate).HasColumnName(@"LicenseExpirationDate").HasColumnType("datetime").IsOptional();
            Property(x => x.BindBank).HasColumnName(@"BindBank").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.BankAccountName).HasColumnName(@"BankAccountName").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.BankAccount).HasColumnName(@"BankAccount").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BankProvince).HasColumnName(@"BankProvince").HasColumnType("int").IsOptional();
            Property(x => x.BankCity).HasColumnName(@"BankCity").HasColumnType("int").IsOptional();
            Property(x => x.BankDistrict).HasColumnName(@"BankDistrict").HasColumnType("int").IsOptional();
            Property(x => x.BankBranch).HasColumnName(@"BankBranch").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.BankCardImg).HasColumnName(@"BankCardImg").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(8000);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.Remark).HasColumnName(@"Remark").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.StoreType).HasColumnName(@"StoreType").HasColumnType("int").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.StoreLogo).HasColumnName(@"StoreLogo").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.BusinessCategoryId).HasColumnName(@"BusinessCategoryID").HasColumnType("int").IsOptional();
            Property(x => x.BusinessHours).HasColumnName(@"BusinessHours").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.ContactName).HasColumnName(@"ContactName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ContactMobile).HasColumnName(@"ContactMobile").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.LicenseName).HasColumnName(@"LicenseName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.BankAccountType).HasColumnName(@"BankAccountType").HasColumnType("int").IsOptional();
            Property(x => x.IndustryLicenses).HasColumnName(@"IndustryLicenses").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.StoreMobile).HasColumnName(@"StoreMobile").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ApprovalStatus).HasColumnName(@"ApprovalStatus").HasColumnType("int").IsOptional();
            Property(x => x.TemporaryServiceFee).HasColumnName(@"TemporaryServiceFee").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.BankCode).HasColumnName(@"BankCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ServiceCode).HasColumnName(@"ServiceCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Images).HasColumnName(@"Images").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("decimal").IsOptional().HasPrecision(18,8);
            Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("decimal").IsOptional().HasPrecision(18,8);
            Property(x => x.ApprovalTime).HasColumnName(@"ApprovalTime").HasColumnType("datetime").IsOptional();
            Property(x => x.ApprovalNote).HasColumnName(@"ApprovalNote").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
        }
    }

}
// </auto-generated>
