// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // OperationCenteApplication
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OperationCenteApplication
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 营运中心名称
        ///</summary>
        public string OperationCenteName { get; set; } // OperationCenteName (length: 128)

        ///<summary>
        /// 发起人的商家id
        ///</summary>
        public System.Guid? OwnerUniqueId { get; set; } // OwnerUniqueID

        ///<summary>
        /// 所属商家的GW号
        ///</summary>
        public string OwnerCode { get; set; } // OwnerCode (length: 50)

        ///<summary>
        /// 所属商家的手机号
        ///</summary>
        public string Mobile { get; set; } // Mobile (length: 50)
        public int? Country { get; set; } // Country
        public int? Province { get; set; } // Province
        public int? City { get; set; } // City
        public int? District { get; set; } // District

        ///<summary>
        /// 0、已删除 1、已添加合伙人 2、审批通过3、审批不通过 4、已创建 5、已提交 6、已过期，取消
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 关联营运中心唯一ID
        ///</summary>
        public System.Guid? OperationCenteUniqueId { get; set; } // OperationCenteUniqueID

        ///<summary>
        /// 审批信息，Json格式存储。
        ///</summary>
        public string ApproveInfo { get; set; } // ApproveInfo

        ///<summary>
        /// 联系人姓名
        ///</summary>
        public string ContactPersonName { get; set; } // ContactPersonName (length: 50)

        ///<summary>
        /// 联系人电话
        ///</summary>
        public string ContactMobile { get; set; } // ContactMobile (length: 50)

        ///<summary>
        /// 对接邮箱
        ///</summary>
        public string ContactEmail { get; set; } // ContactEmail (length: 50)

        ///<summary>
        /// 公司名称
        ///</summary>
        public string EnterpriseName { get; set; } // EnterpriseName (length: 200)

        ///<summary>
        /// 公司法人姓名
        ///</summary>
        public string EnterpriseLegalPersonName { get; set; } // EnterpriseLegalPersonName (length: 50)

        ///<summary>
        /// 公司所在地址
        ///</summary>
        public string EnterpriseAddress { get; set; } // EnterpriseAddress (length: 500)

        ///<summary>
        /// 营业执照图片
        ///</summary>
        public string BusinessLicense { get; set; } // BusinessLicense (length: 1000)

        ///<summary>
        /// 合伙人 存Json(Key:合伙人GW号 Value:合伙人提供的服务码数量)
        ///</summary>
        public string Partners { get; set; } // partners
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 发起人承诺的服务码数量
        ///</summary>
        public int? PromiseServiceCodeNumber { get; set; } // PromiseServiceCodeNumber

        public OperationCenteApplication()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
