// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // OperationCenter
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OperationCenterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OperationCenter>
    {
        public OperationCenterConfiguration()
            : this("dbo")
        {
        }

        public OperationCenterConfiguration(string schema)
        {
            ToTable("OperationCenter", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AgentUniqueId).HasColumnName(@"AgentUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.OwnerUniqueId).HasColumnName(@"OwnerUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.OwnerCode).HasColumnName(@"OwnerCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Mobile).HasColumnName(@"Mobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Country).HasColumnName(@"Country").HasColumnType("int").IsOptional();
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("int").IsOptional();
            Property(x => x.City).HasColumnName(@"City").HasColumnType("int").IsOptional();
            Property(x => x.District).HasColumnName(@"District").HasColumnType("int").IsOptional();
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.RewardRules).HasColumnName(@"RewardRules").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.EnterpriseUniqeuId).HasColumnName(@"EnterpriseUniqeuID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Partners).HasColumnName(@"Partners").HasColumnType("nvarchar(max)").IsOptional();
        }
    }

}
// </auto-generated>
