// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // OperationCenterStatistics
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OperationCenterStatisticConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OperationCenterStatistic>
    {
        public OperationCenterStatisticConfiguration()
            : this("dbo")
        {
        }

        public OperationCenterStatisticConfiguration(string schema)
        {
            ToTable("OperationCenterStatistics", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OperationCenterUniqueId).HasColumnName(@"OperationCenterUniqueID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.StatisticsType).HasColumnName(@"StatisticsType").HasColumnType("int").IsOptional();
            Property(x => x.SupermarketUniqueId).HasColumnName(@"SupermarketUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.StoreUniqueId).HasColumnName(@"StoreUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.SupermarketRevenueIncrease).HasColumnName(@"SupermarketRevenueIncrease").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.StoreOwnedMemberIncrease).HasColumnName(@"StoreOwnedMemberIncrease").HasColumnType("int").IsOptional();
            Property(x => x.StoreIncrease).HasColumnName(@"StoreIncrease").HasColumnType("int").IsOptional();
            Property(x => x.SupermarketIncrease).HasColumnName(@"SupermarketIncrease").HasColumnType("int").IsOptional();
            Property(x => x.StatisticsDateTime).HasColumnName(@"StatisticsDateTime").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
