// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // OperationCenterStatistics
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OperationCenterStatistic
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 营运中心唯一ID
        ///</summary>
        public System.Guid OperationCenterUniqueId { get; set; } // OperationCenterUniqueID

        ///<summary>
        /// 1:销售网点 2:店铺
        ///</summary>
        public int? StatisticsType { get; set; } // StatisticsType

        ///<summary>
        /// 门店唯一ID
        ///</summary>
        public System.Guid? SupermarketUniqueId { get; set; } // SupermarketUniqueID

        ///<summary>
        /// 店铺唯一ID
        ///</summary>
        public System.Guid? StoreUniqueId { get; set; } // StoreUniqueID

        ///<summary>
        /// 门店新增营业额[每天]
        ///</summary>
        public decimal? SupermarketRevenueIncrease { get; set; } // SupermarketRevenueIncrease

        ///<summary>
        /// 店铺新增归属会员数[每天]
        ///</summary>
        public int? StoreOwnedMemberIncrease { get; set; } // StoreOwnedMemberIncrease

        ///<summary>
        /// 新增店铺数[每天]
        ///</summary>
        public int? StoreIncrease { get; set; } // StoreIncrease

        ///<summary>
        /// 新增门店数[每天]
        ///</summary>
        public int? SupermarketIncrease { get; set; } // SupermarketIncrease

        ///<summary>
        /// 统计时间
        ///</summary>
        public System.DateTime StatisticsDateTime { get; set; } // StatisticsDateTime
    }

}
// </auto-generated>
