// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // OperationCenter
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class OperationCenter
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 对应于核心的代理唯一ID，核心用代理来标识一个运营中心
        ///</summary>
        public System.Guid? AgentUniqueId { get; set; } // AgentUniqueID

        ///<summary>
        /// 营运中心名称
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 发起人的商家id
        ///</summary>
        public System.Guid? OwnerUniqueId { get; set; } // OwnerUniqueID

        ///<summary>
        /// 所属商家的GW号
        ///</summary>
        public string OwnerCode { get; set; } // OwnerCode (length: 50)

        ///<summary>
        /// 所属商家的手机号
        ///</summary>
        public string Mobile { get; set; } // Mobile (length: 50)
        public int? Country { get; set; } // Country
        public int? Province { get; set; } // Province
        public int? City { get; set; } // City
        public int? District { get; set; } // District

        ///<summary>
        /// 详细地址
        ///</summary>
        public string Address { get; set; } // Address (length: 4000)

        ///<summary>
        /// 优惠规则
        ///</summary>
        public string RewardRules { get; set; } // RewardRules (length: 4000)
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 状态：0删除2未落地3停用4已落地
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 企业ID
        ///</summary>
        public System.Guid? EnterpriseUniqeuId { get; set; } // EnterpriseUniqeuID

        ///<summary>
        /// 合伙人
        ///</summary>
        public string Partners { get; set; } // Partners

        public OperationCenter()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
