// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // PointCommissionSaleSource
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class PointCommissionSaleSource
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 挂单源编号
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 用户ID
        ///</summary>
        public System.Guid? UserUniqueId { get; set; } // UserUniqueID

        ///<summary>
        /// 盖网号
        ///</summary>
        public string UserCode { get; set; } // UserCode (length: 50)

        ///<summary>
        /// 挂单类型：1：待绑定积分（可以提供用户收益绑定）2：非绑定积分（不提供用户收益绑定）
        ///</summary>
        public int? Type { get; set; } // Type

        ///<summary>
        /// 挂单总额
        ///</summary>
        public decimal? Amount { get; set; } // Amount

        ///<summary>
        /// 挂单剩余金额
        ///</summary>
        public decimal? AmountRemain { get; set; } // AmountRemain

        ///<summary>
        /// 付给盖粉现金和盖粉所提供的积分的比率
        ///</summary>
        public int? Discount { get; set; } // Discount

        ///<summary>
        /// 挂单状态：1：正常；2：冻结；3：撤销
        ///</summary>
        public int? Status { get; set; } // Status
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public PointCommissionSaleSource()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
