// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // PointCommissionSaleSourceRelation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class PointCommissionSaleSourceRelation
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 挂单源ID
        ///</summary>
        public System.Guid? PointCommissionSaleSourceUniqueId { get; set; } // PointCommissionSaleSourceUniqueID

        ///<summary>
        /// 挂单ID
        ///</summary>
        public System.Guid? PointCommissionSaleUniqueId { get; set; } // PointCommissionSaleUniqueID

        ///<summary>
        /// 挂单源提取金额
        ///</summary>
        public decimal? CommissionAmount { get; set; } // CommissionAmount

        ///<summary>
        /// 挂单类型：1：待绑定；2：非绑定
        ///</summary>
        public int? CommissionType { get; set; } // CommissionType
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public PointCommissionSaleSourceRelation()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
