// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // ProductStock
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductStock
    {
        public long Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 销售网点类型
        ///</summary>
        public int? SalesOutletType { get; set; } // SalesOutletType

        ///<summary>
        /// 销售网点ID
        ///</summary>
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID

        ///<summary>
        /// 商品ID
        ///</summary>
        public System.Guid? ProductUniqueId { get; set; } // ProductUniqueID

        ///<summary>
        /// 库存
        ///</summary>
        public int? Stock { get; set; } // Stock
        public int? FrozenStock { get; set; } // FrozenStock
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? LineId { get; set; } // LineID

        public ProductStock()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
