// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // ProductBarcodeInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ProductBarcodeInfo
    {
        public long Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 条形码
        ///</summary>
        public string Barcode { get; set; } // Barcode (length: 16)

        ///<summary>
        /// 名称
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 品牌
        ///</summary>
        public string Brand { get; set; } // Brand (length: 64)

        ///<summary>
        /// 分类ID
        ///</summary>
        public long? CategoryId { get; set; } // CategoryID

        ///<summary>
        /// 分类名称
        ///</summary>
        public string CategoryName { get; set; } // CategoryName (length: 128)

        ///<summary>
        /// 默认价格
        ///</summary>
        public decimal? DefaultPrice { get; set; } // DefaultPrice

        ///<summary>
        /// 缩略图
        ///</summary>
        public string Thumbnail { get; set; } // Thumbnail (length: 128)

        ///<summary>
        /// 规格
        ///</summary>
        public string Specification { get; set; } // Specification (length: 128)

        ///<summary>
        /// 单位
        ///</summary>
        public string Unit { get; set; } // Unit (length: 25)

        ///<summary>
        /// 是否自定义商品 0：否 1：是，如果是商家录入是自定义的
        ///</summary>
        public int? SubmitByMerchant { get; set; } // SubmitByMerchant

        ///<summary>
        /// 状态：0：未启用 1：已启用
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 商品描述
        ///</summary>
        public string Description { get; set; } // Description

        ///<summary>
        /// 创建者盖网号
        ///</summary>
        public string CreatorUserCode { get; set; } // CreatorUserCode (length: 20)

        ///<summary>
        /// 创建者ID
        ///</summary>
        public int? CreatorId { get; set; } // CreatorID

        ///<summary>
        /// 商品图片
        ///</summary>
        public string ProductPictures { get; set; } // ProductPictures
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public ProductBarcodeInfo()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
