// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // RequestRecord
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class RequestRecord
    {
        public long Id { get; set; } // ID (Primary key)
        public string Signature { get; set; } // Signature (length: 200)
        public string InterfaceUrl { get; set; } // InterfaceURL (length: 200)
        public System.DateTime? CreateTime { get; set; } // CreateTime

        public RequestRecord()
        {
            CreateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
