// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SalesClerk
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SalesClerk
    {
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 商店所属者ID
        ///</summary>
        public System.Guid? StoreOwnerUniqueId { get; set; } // StoreOwnerUniqueID

        ///<summary>
        /// 商店ID
        ///</summary>
        public System.Guid? StoreUniqueId { get; set; } // StoreUniqueID

        ///<summary>
        /// 销售网点ID
        ///</summary>
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID

        ///<summary>
        /// 店小二用户ID
        ///</summary>
        public System.Guid? UserUniqueId { get; set; } // UserUniqueID

        ///<summary>
        /// 状态：0：无效；1：有效
        ///</summary>
        public int? Status { get; set; } // Status
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int Id { get; set; } // ID (Primary key)
    }

}
// </auto-generated>
