// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SalesOutletConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SalesOutletConfig
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string SalesOutletCode { get; private set; } // SalesOutletCode (length: 8000)

        ///<summary>
        /// 门店名称
        ///</summary>
        public string Name { get; set; } // Name (length: 200)

        ///<summary>
        /// 销售网点ID
        ///</summary>
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID

        ///<summary>
        /// 是否支持快捷支付
        ///</summary>
        public bool? SupportQuickPay { get; set; } // SupportQuickPay

        ///<summary>
        /// 优惠类型：1：无优惠；2：按比率优惠；3：满多少减多少（有上限）；4：满多少减多少（无上限）
        ///</summary>
        public int? DiscountType { get; set; } // DiscountType

        ///<summary>
        /// 优惠金额
        ///</summary>
        public decimal? DiscountAmount { get; set; } // DiscountAmount

        ///<summary>
        /// 使用优惠的最小订单金额
        ///</summary>
        public decimal? MinSalesOrderAmountOfDiscount { get; set; } // MinSalesOrderAmountOfDiscount

        ///<summary>
        /// 最大优惠金额
        ///</summary>
        public decimal? MaxDiscountAmount { get; set; } // MaxDiscountAmount

        ///<summary>
        /// 优惠折扣
        ///</summary>
        public decimal? DiscountRatio { get; set; } // DiscountRatio

        ///<summary>
        /// 推送号码
        ///</summary>
        public string PushMobile { get; set; } // PushMobile (length: 64)
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 盖网服务费率
        ///</summary>
        public int? ServiceFee { get; set; } // ServiceFee

        ///<summary>
        /// 推荐服务费率
        ///</summary>
        public int? RecommendServiceFee { get; set; } // RecommendServiceFee

        ///<summary>
        /// 排序
        ///</summary>
        public int? SortOrder { get; set; } // SortOrder

        ///<summary>
        /// 0:门店；1：售货机；2：盖鲜生
        ///</summary>
        public int? SalesOutletType { get; set; } // SalesOutletType

        public SalesOutletConfig()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
