// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SalesOutletApprove
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SalesOutletApprove
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 商店唯一ID
        ///</summary>
        public System.Guid? StoreUniqueId { get; set; } // StoreUniqueID

        ///<summary>
        /// 销售网点信息
        ///</summary>
        public string SalesOutletInfo { get; set; } // SalesOutletInfo

        ///<summary>
        /// 0.申请中  1.码主同意绑定销售网点  2.码主拒绝绑定销售网点  3.营运中心确认费率  4.渠道审核通过  5.渠道审核不通过
        ///</summary>
        public int? ApproveStatus { get; set; } // ApproveStatus

        ///<summary>
        /// 审批意见
        ///</summary>
        public string ApprovalNote { get; set; } // ApprovalNote (length: 4000)

        ///<summary>
        /// 最近审批时间
        ///</summary>
        public System.DateTime? ApprovalTime { get; set; } // ApprovalTime
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 销售渠道类型
        ///</summary>
        public int? SalesOutletType { get; set; } // SalesOutletType

        ///<summary>
        /// 服务码
        ///</summary>
        public string ServiceCode { get; set; } // ServiceCode (length: 50)

        ///<summary>
        /// 服务码绑定的商家盖网号
        ///</summary>
        public string MerchantCode { get; set; } // MerchantCode (length: 50)

        public SalesOutletApprove()
        {
            CreateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
