// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SalesOutletApprove
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SalesOutletApproveConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesOutletApprove>
    {
        public SalesOutletApproveConfiguration()
            : this("dbo")
        {
        }

        public SalesOutletApproveConfiguration(string schema)
        {
            ToTable("SalesOutletApprove", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StoreUniqueId).HasColumnName(@"StoreUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.SalesOutletInfo).HasColumnName(@"SalesOutletInfo").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ApproveStatus).HasColumnName(@"ApproveStatus").HasColumnType("int").IsOptional();
            Property(x => x.ApprovalNote).HasColumnName(@"ApprovalNote").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.ApprovalTime).HasColumnName(@"ApprovalTime").HasColumnType("datetime").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.SalesOutletType).HasColumnName(@"SalesOutletType").HasColumnType("int").IsOptional();
            Property(x => x.ServiceCode).HasColumnName(@"ServiceCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MerchantCode).HasColumnName(@"MerchantCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
        }
    }

}
// </auto-generated>
