// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // ServiceCodeBindRecord
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ServiceCodeBindRecord
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 商家管理者盖网号
        ///</summary>
        public string OwnerCode { get; set; } // OwnerCode (length: 50)

        ///<summary>
        /// 服务码
        ///</summary>
        public string ServiceCode { get; set; } // ServiceCode (length: 50)
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 营运中心唯一ID
        ///</summary>
        public System.Guid? OperationCenterUniqueId { get; set; } // OperationCenterUniqueID

        ///<summary>
        /// 1：Normal 等待绑定  2：Aggreed 同意绑定  3：Rejected 拒绝绑定  4：OutDate 过期
        ///</summary>
        public int? Status { get; set; } // Status

        public ServiceCodeBindRecord()
        {
            CreateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
