// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ServiceGetPointSaleRulesByStatusReturnModel
    {
        public System.Int64 ID { get; set; }
        public System.Guid UniqueID { get; set; }
        public System.String Code { get; set; }
        public System.Guid? PointCommissionSaleUniqueID { get; set; }
        public System.String Title { get; set; }
        public System.Int32? Type { get; set; }
        public System.Decimal? GiveAmount { get; set; }
        public System.Decimal? PointAmount { get; set; }
        public System.Decimal? Price { get; set; }
        public System.Decimal? SaleMaxLimit { get; set; }
        public System.Decimal? SaleAmount { get; set; }
        public System.Int32? PriReturnStageNumber { get; set; }
        public System.Int32? GiveReturnStageNumber { get; set; }
        public System.Int32? StageLength { get; set; }
        public System.String Remark { get; set; }
        public System.Int32? Status { get; set; }
        public System.DateTime? CreateTime { get; set; }
        public System.DateTime? UpdateTime { get; set; }
    }

}
// </auto-generated>
