// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // ServiceCodeOwner
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ServiceCodeOwner
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// 商户管理者名称
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 商户管理者的商家id
        ///</summary>
        public System.Guid? MerchantUniqueId { get; set; } // MerchantUniqueID

        ///<summary>
        /// 所属商家盖网号
        ///</summary>
        public string MerchantCode { get; set; } // MerchantCode (length: 50)

        ///<summary>
        /// 所属商家的手机号
        ///</summary>
        public string Mobile { get; set; } // Mobile (length: 50)
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public ServiceCodeOwner()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
