// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SuperMarket
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SuperMarketConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SuperMarket>
    {
        public SuperMarketConfiguration()
            : this("dbo")
        {
        }

        public SuperMarketConfiguration(string schema)
        {
            ToTable("SuperMarket", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.MerchantUniqueId).HasColumnName(@"MerchantUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.MerchantCode).HasColumnName(@"MerchantCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BusinessCategoryId).HasColumnName(@"BusinessCategoryID").HasColumnType("int").IsOptional();
            Property(x => x.Mobile).HasColumnName(@"Mobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.Logo).HasColumnName(@"Logo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("int").IsOptional();
            Property(x => x.ProvinceName).HasColumnName(@"ProvinceName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("int").IsOptional();
            Property(x => x.CityName).HasColumnName(@"CityName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.District).HasColumnName(@"District").HasColumnType("int").IsOptional();
            Property(x => x.DistrictName).HasColumnName(@"DistrictName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PostCode).HasColumnName(@"PostCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(16);
            Property(x => x.IsSupportDelivery).HasColumnName(@"IsSupportDelivery").HasColumnType("bit").IsOptional();
            Property(x => x.DeliveryTimeRange).HasColumnName(@"DeliveryTimeRange").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(25);
            Property(x => x.MinAmountOfDelivery).HasColumnName(@"MinAmountOfDelivery").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.MinAmountOfFreeDelivery).HasColumnName(@"MinAmountOfFreeDelivery").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.DeliveryFee).HasColumnName(@"DeliveryFee").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("float").IsOptional();
            Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("float").IsOptional();
            Property(x => x.BusinessHours).HasColumnName(@"BusinessHours").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.IsRecommend).HasColumnName(@"IsRecommend").HasColumnType("bit").IsOptional();
            Property(x => x.RecommendPosition).HasColumnName(@"RecommendPosition").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(64);
            Property(x => x.CosumeLimitOfPersonPerday).HasColumnName(@"CosumeLimitOfPersonPerday").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.SoldProductNumber).HasColumnName(@"SoldProductNumber").HasColumnType("int").IsOptional();
            Property(x => x.ReferralsUniqueId).HasColumnName(@"ReferralsUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.PushMobile).HasColumnName(@"PushMobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(64);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.StoreUniqueId).HasColumnName(@"StoreUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Images).HasColumnName(@"Images").HasColumnType("nvarchar").IsOptional().HasMaxLength(4000);
            Property(x => x.KeyWords).HasColumnName(@"KeyWords").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.Introduction).HasColumnName(@"Introduction").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.DeliveryDistanceRange).HasColumnName(@"DeliveryDistanceRange").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
