// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncPointWholesaleConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncPointWholesaleConfigConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SyncPointWholesaleConfig>
    {
        public SyncPointWholesaleConfigConfiguration()
            : this("dbo")
        {
        }

        public SyncPointWholesaleConfigConfiguration(string schema)
        {
            ToTable("SyncPointWholesaleConfig", schema);
            HasKey(x => new { x.Id, x.UniqueId });

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.MaxWholesaleAmount).HasColumnName(@"MaxWholesaleAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.MaxWholesaleAmountPerMonth).HasColumnName(@"MaxWholesaleAmountPerMonth").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.MerchantProfitRatio).HasColumnName(@"MerchantProfitRatio").HasColumnType("int").IsOptional();
            Property(x => x.SaleRules).HasColumnName(@"SaleRules").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("datetime").IsOptional();
        }
    }

}
// </auto-generated>
