// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncSuperMarket
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncSuperMarketConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SyncSuperMarket>
    {
        public SyncSuperMarketConfiguration()
            : this("dbo")
        {
        }

        public SyncSuperMarketConfiguration(string schema)
        {
            ToTable("SyncSuperMarket", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("bigint").IsRequired();
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.MerchantUniqueId).HasColumnName(@"MerchantUniqueID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BusinessCategoryId).HasColumnName(@"BusinessCategoryID").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Mobile).HasColumnName(@"Mobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.Logo).HasColumnName(@"Logo").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(128);
            Property(x => x.Province).HasColumnName(@"Province").HasColumnType("int").IsOptional();
            Property(x => x.City).HasColumnName(@"City").HasColumnType("int").IsOptional();
            Property(x => x.District).HasColumnName(@"District").HasColumnType("int").IsOptional();
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.PostCode).HasColumnName(@"PostCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(16);
            Property(x => x.IsSupportDelivery).HasColumnName(@"IsSupportDelivery").HasColumnType("bit").IsOptional();
            Property(x => x.DeliveryTimeRange).HasColumnName(@"DeliveryTimeRange").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(25);
            Property(x => x.MinAmountOfDelivery).HasColumnName(@"MinAmountOfDelivery").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.MinAmountOfFreeDelivery).HasColumnName(@"MinAmountOfFreeDelivery").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.DeliveryFee).HasColumnName(@"DeliveryFee").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.Longitude).HasColumnName(@"Longitude").HasColumnType("float").IsOptional();
            Property(x => x.Latitude).HasColumnName(@"Latitude").HasColumnType("float").IsOptional();
            Property(x => x.BusinessHours).HasColumnName(@"BusinessHours").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(25);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.IsRecommend).HasColumnName(@"IsRecommend").HasColumnType("bit").IsOptional();
            Property(x => x.RecommendPosition).HasColumnName(@"RecommendPosition").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(64);
            Property(x => x.CosumeLimitOfPersonPerday).HasColumnName(@"CosumeLimitOfPersonPerday").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.SoldProductNumber).HasColumnName(@"SoldProductNumber").HasColumnType("int").IsOptional();
            Property(x => x.ReferralsUniqueId).HasColumnName(@"ReferralsUniqueID").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SupportQuickPay).HasColumnName(@"SupportQuickPay").HasColumnType("bit").IsOptional();
            Property(x => x.DiscountType).HasColumnName(@"DiscountType").HasColumnType("int").IsOptional();
            Property(x => x.MinSalesOrderAmountOfDiscount).HasColumnName(@"MinSalesOrderAmountOfDiscount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.DiscountAmount).HasColumnName(@"DiscountAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.MaxDiscountAmount).HasColumnName(@"MaxDiscountAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.DiscountRatio).HasColumnName(@"DiscountRatio").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.PushMobile).HasColumnName(@"PushMobile").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(64);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.TempMerchantId).HasColumnName(@"TempMerchantID").HasColumnType("int").IsOptional();
            Property(x => x.TempBusinessCategoryId).HasColumnName(@"TempBusinessCategoryID").HasColumnType("int").IsOptional();
            Property(x => x.TempReferralsUserCode).HasColumnName(@"TempReferralsUserCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.MerchantCode).HasColumnName(@"MerchantCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.StoreUniqueId).HasColumnName(@"StoreUniqueID").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.ProvinceName).HasColumnName(@"ProvinceName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.CityName).HasColumnName(@"CityName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.DistrictName).HasColumnName(@"DistrictName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

}
// </auto-generated>
