// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncGXSPosDealInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncGxsPosDealInfo
    {

        ///<summary>
        /// 唯一主键ID
        ///</summary>
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// ID,自增长
        ///</summary>
        public long Id { get; set; } // ID

        ///<summary>
        /// 编码
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 用户ID
        ///</summary>
        public string UserUniqueId { get; set; } // UserUniqueID (length: 50)

        ///<summary>
        /// 电话
        ///</summary>
        public string Phone { get; set; } // Phone (length: 32)

        ///<summary>
        /// 卡号
        ///</summary>
        public string CardNo { get; set; } // CardNO (length: 50)

        ///<summary>
        /// 金额
        ///</summary>
        public decimal? Amount { get; set; } // Amount

        ///<summary>
        /// 流水号
        ///</summary>
        public string SerialNo { get; set; } // SerialNO (length: 50)

        ///<summary>
        /// 交易时间
        ///</summary>
        public System.DateTime? TransactionTime { get; set; } // TransactionTime

        ///<summary>
        /// 支付平台分配给盖网的商户号
        ///</summary>
        public string BusinessNo { get; set; } // BusinessNO (length: 100)

        ///<summary>
        /// 设备终端号
        ///</summary>
        public string DeviceNo { get; set; } // DeviceNO (length: 100)

        ///<summary>
        /// 签约时留下的商户名称
        ///</summary>
        public string MerchantName { get; set; } // MerchantName (length: 100)

        ///<summary>
        /// POS机操作员
        ///</summary>
        public System.Guid? OperatorUniqueId { get; set; } // OperatorUniqueID

        ///<summary>
        /// 支付凭证号
        ///</summary>
        public string PaymentRreceiptNo { get; set; } // PaymentRreceiptNO (length: 100)

        ///<summary>
        /// 批次号
        ///</summary>
        public string BatchNo { get; set; } // BatchNO (length: 100)

        ///<summary>
        /// 银行卡片有效期
        ///</summary>
        public System.DateTime? CardValidDate { get; set; } // CardValidDate

        ///<summary>
        /// 交易类型
        ///</summary>
        public string TransactionType { get; set; } // TransactionType (length: 17)

        ///<summary>
        /// 发卡银行
        ///</summary>
        public string BankOfCard { get; set; } // BankOfCard (length: 100)

        ///<summary>
        /// 收单银行
        ///</summary>
        public string BankOfReceive { get; set; } // BankOfReceive (length: 100)

        ///<summary>
        /// 清算日期
        ///</summary>
        public System.DateTime? AccountClearDate { get; set; } // AccountClearDate

        ///<summary>
        /// 订单ID
        ///</summary>
        public string SalesOrderId { get; set; } // SalesOrderID (length: 50)

        ///<summary>
        /// 创建时间
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempSalesOrderId { get; set; } // TempSalesOrderID
        public int? TempOperatorId { get; set; } // TempOperatorID
        public string TempUserCode { get; set; } // TempUserCode (length: 50)

        public SyncGxsPosDealInfo()
        {
            UniqueId = System.Guid.NewGuid();
            Amount = 0m;
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
