// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncMerchantReward
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncMerchantReward
    {
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public long Id { get; set; } // ID (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public System.Guid? MerchantUniqueId { get; set; } // MerchantUniqueID
        public string MerchantName { get; set; } // MerchantName (length: 128)
        public string MerchantCode { get; set; } // MerchantCode (length: 50)
        public string Mobile { get; set; } // Mobile (length: 128)
        public System.Guid? OperatorUniqueId { get; set; } // OperatorUniqueID
        public string OperatorName { get; set; } // OperatorName (length: 128)
        public int? PassedStageNumber { get; set; } // PassedStageNumber
        public int? TotalStageNumber { get; set; } // TotalStageNumber
        public int? StageInterval { get; set; } // StageInterval
        public decimal? TotalRewardAmount { get; set; } // TotalRewardAmount
        public decimal? RewardPerStage { get; set; } // RewardPerStage
        public int? Status { get; set; } // Status
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempOperatorId { get; set; } // TempOperatorID

        public SyncMerchantReward()
        {
            UniqueId = System.Guid.NewGuid();
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
