// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncProductStock
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncProductStock
    {
        public long Id { get; set; } // ID (Primary key)
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public int? SalesOutletType { get; set; } // SalesOutletType
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID
        public string ProductUniqueId { get; set; } // ProductUniqueID (length: 50)
        public int? Stock { get; set; } // Stock
        public int? FrozenStock { get; set; } // FrozenStock
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempSalesOutletId { get; set; } // TempSalesOutletID
        public int? TempProductId { get; set; } // TempProductID
        public int? LineId { get; set; } // LineID

        public SyncProductStock()
        {
            UniqueId = System.Guid.NewGuid();
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
