// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncServiceCode
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncServiceCode
    {
        public int Id { get; set; } // ID (Primary key)
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public System.Guid? MerchantUniqueId { get; set; } // MerchantUniqueID
        public string MerchantCode { get; set; } // MerchantCode (length: 50)
        public string OwnerUniqueId { get; set; } // OwnerUniqueID (length: 50)
        public string OwnerCode { get; set; } // OwnerCode (length: 50)
        public string OperationCenterUniqueId { get; set; } // OperationCenterUniqueID (length: 50)
        public string OperationCenterCode { get; set; } // OperationCenterCode (length: 50)
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID
        public int? SalesOutletType { get; set; } // SalesOutletType
        public bool? IsBind { get; set; } // IsBind
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? ApproveStatus { get; set; } // ApproveStatus
        public int? Type { get; set; } // Type
        public string MerchantName { get; set; } // MerchantName (length: 50)
        public string OrderCode { get; set; } // OrderCode (length: 50)

        public SyncServiceCode()
        {
            UniqueId = System.Guid.NewGuid();
            IsBind = false;
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
            Type = 0;
        }
    }

}
// </auto-generated>
