// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncSalesOutletGPSInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncSalesOutletGpsInfo
    {

        ///<summary>
        /// 唯一主键ID
        ///</summary>
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// ID,自增长
        ///</summary>
        public long Id { get; set; } // ID

        ///<summary>
        /// 编码
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 销售网点类型：1：门店；2：售货机；3：生鲜机
        ///</summary>
        public int? SalesOutletType { get; set; } // SalesOutletType

        ///<summary>
        /// 网点ID
        ///</summary>
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID

        ///<summary>
        /// 经度
        ///</summary>
        public double? Longitude { get; set; } // Longitude

        ///<summary>
        /// 纬度
        ///</summary>
        public double? Latitude { get; set; } // Latitude

        ///<summary>
        /// 状态：0：申请；1：启用；2：禁用
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 是否推荐
        ///</summary>
        public bool? IsRecommend { get; set; } // IsRecommend

        ///<summary>
        /// 创建时间
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempSalesOutletId { get; set; } // TempSalesOutletID

        public SyncSalesOutletGpsInfo()
        {
            UniqueId = System.Guid.NewGuid();
            SalesOutletType = 1;
            Longitude = 0;
            Latitude = 0;
            IsRecommend = false;
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
