// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncSalesClerk
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncSalesClerkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SyncSalesClerk>
    {
        public SyncSalesClerkConfiguration()
            : this("dbo")
        {
        }

        public SyncSalesClerkConfiguration(string schema)
        {
            ToTable("SyncSalesClerk", schema);
            HasKey(x => new { x.Id, x.UniqueId });

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.StoreOwnerUniqueId).HasColumnName(@"StoreOwnerUniqueID").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.StoreUniqueId).HasColumnName(@"StoreUniqueID").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.SalesOutletUniqueId).HasColumnName(@"SalesOutletUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.UserUniqueId).HasColumnName(@"UserUniqueID").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.TempStoreOwnerCode).HasColumnName(@"TempStoreOwnerCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.TempUserCode).HasColumnName(@"TempUserCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
        }
    }

}
// </auto-generated>
