// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncAdvertisePosition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncAdvertisePosition
    {
        public int Id { get; set; } // ID (Primary key)
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public int? AppId { get; set; } // AppID
        public string Name { get; set; } // Name (length: 128)
        public string Code { get; set; } // Code (length: 50)
        public string Content { get; set; } // Content
        public int? Type { get; set; } // Type
        public int? Status { get; set; } // Status
        public int? Width { get; set; } // Width
        public int? Height { get; set; } // Height
        public int? Clicks { get; set; } // Clicks
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public SyncAdvertisePosition()
        {
            UniqueId = System.Guid.NewGuid();
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
