// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncGXSProduct
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncGxsProduct
    {
        public long Id { get; set; } // ID (Primary key)
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public string ProductUniqueId { get; set; } // ProductUniqueID (length: 50)
        public System.Guid? MachineUniqueId { get; set; } // MachineUniqueID
        public int? LineId { get; set; } // LineID
        public string LineCode { get; set; } // LineCode (length: 32)
        public int? Status { get; set; } // Status
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpateTime { get; set; } // UpateTime
        public int? TempProductId { get; set; } // TempProductID
        public int? TempMachineId { get; set; } // TempMachineID
        public int? TempLineId { get; set; } // TempLineID
        public string ProductName { get; set; } // ProductName (length: 500)
        public string StoreCategoryId { get; set; } // StoreCategoryID (length: 50)
        public string StoreCategoryName { get; set; } // StoreCategoryName (length: 200)
        public string Barcode { get; set; } // Barcode (length: 50)

        public SyncGxsProduct()
        {
            UniqueId = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
