// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncMerchantRewardHistory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncMerchantRewardHistory
    {
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public long Id { get; set; } // ID (Primary key)
        public string Code { get; set; } // Code (Primary key) (length: 50)
        public System.Guid? MerchantUniqueId { get; set; } // MerchantUniqueID
        public string MerchantCode { get; set; } // MerchantCode (length: 50)
        public System.Guid? OperatorUniqueId { get; set; } // OperatorUniqueID
        public string OperatorName { get; set; } // OperatorName (length: 128)
        public System.Guid? RewardUniqueId { get; set; } // RewardUniqueID
        public decimal? Reward { get; set; } // Reward
        public int? Status { get; set; } // Status
        public System.DateTime? DeliverTime { get; set; } // DeliverTime
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempRewardId { get; set; } // TempRewardID
        public int? TempOperatorId { get; set; } // TempOperatorID

        public SyncMerchantRewardHistory()
        {
            UniqueId = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
