// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncPointCommissionSaleSourceRelation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncPointCommissionSaleSourceRelation
    {
        public int Id { get; set; } // ID (Primary key)
        public System.Guid? UniqueId { get; set; } // UniqueID
        public System.Guid? PointCommissionSaleSourceUniqueId { get; set; } // PointCommissionSaleSourceUniqueID
        public System.Guid? PointCommissionSaleUniqueId { get; set; } // PointCommissionSaleUniqueID
        public decimal? CommissionAmount { get; set; } // CommissionAmount
        public int? CommissionType { get; set; } // CommissionType
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempPointCommissionSaleSourceId { get; set; } // TempPointCommissionSaleSourceID
        public int? TempPointCommissionSaleId { get; set; } // TempPointCommissionSaleID

        public SyncPointCommissionSaleSourceRelation()
        {
            UniqueId = System.Guid.NewGuid();
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
