// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncGXSLineInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncGxsLineInfo
    {
        public int Id { get; set; } // ID (Primary key)
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 128)
        public string RenterUniqueId { get; set; } // RenterUniqueID (length: 50)
        public System.Guid? MachineUniqueId { get; set; } // MachineUniqueID
        public string Name { get; set; } // Name (length: 128)
        public int? Status { get; set; } // Status
        public System.DateTime? ExpireTime { get; set; } // ExpireTime
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempMachineId { get; set; } // TempMachineID
        public string TempMerchantCode { get; set; } // TempMerchantCode (length: 50)

        public SyncGxsLineInfo()
        {
            UniqueId = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
