// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncVendingMachineProduct
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncVendingMachineProduct
    {

        ///<summary>
        /// 唯一主键ID
        ///</summary>
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// ID,自增长
        ///</summary>
        public long Id { get; set; } // ID

        ///<summary>
        /// 编码
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 商品ID
        ///</summary>
        public string ProductUniqueId { get; set; } // ProductUniqueID (length: 50)

        ///<summary>
        /// 机器ID
        ///</summary>
        public System.Guid? VendingMachineUniqueId { get; set; } // VendingMachineUniqueID

        ///<summary>
        /// 货道
        ///</summary>
        public string Line { get; set; } // Line (length: 32)

        ///<summary>
        /// 状态：1：上架；2：下架
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 创建时间
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 商品ID
        ///</summary>
        public int? TempProductId { get; set; } // TempProductID

        ///<summary>
        /// 机器ID
        ///</summary>
        public int? TempVendingMachineId { get; set; } // TempVendingMachineID
        public string ProductName { get; set; } // ProductName (length: 500)
        public string StoreCategoryId { get; set; } // StoreCategoryID (length: 50)
        public string StoreCategoryName { get; set; } // StoreCategoryName (length: 200)

        public SyncVendingMachineProduct()
        {
            UniqueId = System.Guid.NewGuid();
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
