// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncProductBarcodeInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncProductBarcodeInfo
    {
        public long Id { get; set; } // ID (Primary key)
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)
        public string Barcode { get; set; } // Barcode (length: 16)
        public string Name { get; set; } // Name (length: 128)
        public string Brand { get; set; } // Brand (length: 64)
        public long? CategoryId { get; set; } // CategoryID
        public string CategoryName { get; set; } // CategoryName (length: 128)
        public decimal? DefaultPrice { get; set; } // DefaultPrice
        public string Thumbnail { get; set; } // Thumbnail (length: 128)
        public string Specification { get; set; } // Specification (length: 128)
        public string Unit { get; set; } // Unit (length: 25)
        public int? SubmitByMerchant { get; set; } // SubmitByMerchant
        public int? Status { get; set; } // Status
        public string Description { get; set; } // Description
        public string CreatorUserCode { get; set; } // CreatorUserCode (length: 20)
        public int? CreatorId { get; set; } // CreatorID
        public string ProductPictures { get; set; } // ProductPictures
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime
        public int? TempCategoryId { get; set; } // TempCategoryID

        public SyncProductBarcodeInfo()
        {
            UniqueId = System.Guid.NewGuid();
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
