// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // SyncPointCommissionSale
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SyncPointCommissionSaleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SyncPointCommissionSale>
    {
        public SyncPointCommissionSaleConfiguration()
            : this("dbo")
        {
        }

        public SyncPointCommissionSaleConfiguration(string schema)
        {
            ToTable("SyncPointCommissionSale", schema);
            HasKey(x => new { x.Id, x.UniqueId });

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.BindAmount).HasColumnName(@"BindAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.UnBindAmount).HasColumnName(@"UnBindAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.LeftAmount).HasColumnName(@"LeftAmount").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.BindSize).HasColumnName(@"BindSize").HasColumnType("decimal").IsOptional().HasPrecision(18,5);
            Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("datetime").IsOptional();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
        }
    }

}
// </auto-generated>
