// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // UserOnLine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class UserOnLine
    {
        public int Id { get; set; } // ID
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 用户ID
        ///</summary>
        public System.Guid? UserUniqueId { get; set; } // UserUniqueID

        ///<summary>
        /// 盖网号
        ///</summary>
        public string UserCode { get; set; } // UserCode (length: 50)

        ///<summary>
        /// 用户名
        ///</summary>
        public string UserName { get; set; } // UserName (length: 100)

        ///<summary>
        /// Token
        ///</summary>
        public string Token { get; set; } // Token (length: 32)

        ///<summary>
        /// 登录所在城市
        ///</summary>
        public int? City { get; set; } // City
        public string Ip { get; set; } // IP (length: 50)

        ///<summary>
        /// 设备ID
        ///</summary>
        public int? DeviceId { get; set; } // DeviceID

        ///<summary>
        /// 是否有效
        ///</summary>
        public bool? IsValid { get; set; } // IsValid
        public System.DateTime? CreateTime { get; set; } // CreateTime
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        public UserOnLine()
        {
            CreateTime = System.DateTime.UtcNow;
            UpdateTime = System.DateTime.UtcNow;
        }
    }

}
// </auto-generated>
