// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // UserRegistInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class UserRegistInfo
    {

        ///<summary>
        /// ID
        ///</summary>
        public int Id { get; set; } // ID (Primary key)

        ///<summary>
        /// 唯一ID
        ///</summary>
        public System.Guid? UniqueId { get; set; } // UniqueID

        ///<summary>
        /// 门店唯一ID
        ///</summary>
        public System.Guid? SalesOutletUniqueId { get; set; } // SalesOutletUniqueID

        ///<summary>
        /// 商店唯一ID
        ///</summary>
        public System.Guid? StoreUniqueId { get; set; } // StoreUniqueID

        ///<summary>
        /// 注册方式 １：普通注册 ２：个人扫码 ３：门店扫码
        ///</summary>
        public int? RegistMethod { get; set; } // RegistMethod

        ///<summary>
        /// 注册用户的唯一ID
        ///</summary>
        public System.Guid? UserUniqueId { get; set; } // UserUniqueID

        ///<summary>
        /// 用户名
        ///</summary>
        public string Username { get; set; } // Username (length: 50)

        ///<summary>
        /// 注册时间
        ///</summary>
        public System.DateTime RegisteTime { get; set; } // RegisteTime
    }

}
// </auto-generated>
