// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // VendingMachine
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class VendingMachine
    {

        ///<summary>
        /// 唯一主键ID
        ///</summary>
        public System.Guid UniqueId { get; set; } // UniqueID (Primary key)

        ///<summary>
        /// ID,自增长
        ///</summary>
        public long Id { get; set; } // ID

        ///<summary>
        /// 编码
        ///</summary>
        public string Code { get; set; } // Code (length: 50)

        ///<summary>
        /// 缩略图
        ///</summary>
        public string Logo { get; set; } // Logo (length: 128)

        ///<summary>
        /// 联系人手机号
        ///</summary>
        public string Mobile { get; set; } // Mobile (length: 13)

        ///<summary>
        /// 商家ID
        ///</summary>
        public System.Guid? MerchantUniqueId { get; set; } // MerchantUniqueID

        ///<summary>
        /// 所属商家盖网号
        ///</summary>
        public string MerchantCode { get; set; } // MerchantCode (length: 50)

        ///<summary>
        /// 销售网点分类
        ///</summary>
        public int? BusinessCategoryId { get; set; } // BusinessCategoryID

        ///<summary>
        /// 激活码
        ///</summary>
        public string ActivationCode { get; set; } // ActivationCode (length: 50)

        ///<summary>
        /// 名称
        ///</summary>
        public string Name { get; set; } // Name (length: 128)

        ///<summary>
        /// 密码
        ///</summary>
        public string Password { get; set; } // Password (length: 128)

        ///<summary>
        /// 状态：0：申请；1：启用；2：禁用
        ///</summary>
        public int? Status { get; set; } // Status

        ///<summary>
        /// 是否已激活
        ///</summary>
        public bool? IsActivate { get; set; } // IsActivate

        ///<summary>
        /// 币种
        ///</summary>
        public string Currency { get; set; } // Currency (length: 20)

        ///<summary>
        /// 国家
        ///</summary>
        public int? Country { get; set; } // Country
        public string CountryName { get; set; } // CountryName (length: 50)

        ///<summary>
        /// 省
        ///</summary>
        public int? Province { get; set; } // Province
        public string ProvinceName { get; set; } // ProvinceName (length: 50)

        ///<summary>
        /// 市
        ///</summary>
        public int? City { get; set; } // City
        public string CityName { get; set; } // CityName (length: 50)

        ///<summary>
        /// 区
        ///</summary>
        public int? District { get; set; } // District
        public string DistrictName { get; set; } // DistrictName (length: 50)

        ///<summary>
        /// 地址
        ///</summary>
        public string Address { get; set; } // Address (length: 225)

        ///<summary>
        /// 管理员ID
        ///</summary>
        public System.Guid? MaintainerUniqueId { get; set; } // MaintainerUniqueID

        ///<summary>
        /// 管理的IP
        ///</summary>
        public string MaintainerIp { get; set; } // MaintainerIP (length: 50)

        ///<summary>
        /// 机器安装时间
        ///</summary>
        public System.DateTime? SetupTime { get; set; } // SetupTime

        ///<summary>
        /// 备注
        ///</summary>
        public string Remark { get; set; } // Remark (length: 200)

        ///<summary>
        /// 私钥
        ///</summary>
        public string PrivateKey { get; set; } // PrivateKey

        ///<summary>
        /// 公钥
        ///</summary>
        public string PublicKey { get; set; } // PublicKey

        ///<summary>
        /// 设备ID
        ///</summary>
        public string DeviceId { get; set; } // DeviceID (length: 100)

        ///<summary>
        /// 经度
        ///</summary>
        public double? Longitude { get; set; } // Longitude

        ///<summary>
        /// 纬度
        ///</summary>
        public double? Latitude { get; set; } // Latitude

        ///<summary>
        /// 是否推荐
        ///</summary>
        public bool? IsRecommend { get; set; } // IsRecommend

        ///<summary>
        /// 推荐位置
        ///</summary>
        public string RecommendPosition { get; set; } // RecommendPosition (length: 64)

        ///<summary>
        /// 推荐人ID
        ///</summary>
        public System.Guid? ReferralsUniqueId { get; set; } // ReferralsUniqueID

        ///<summary>
        /// 故障码
        ///</summary>
        public int? ErrorCode { get; set; } // ErrorCode

        ///<summary>
        /// 机器软件版本号
        ///</summary>
        public string Version { get; set; } // Version (length: 12)

        ///<summary>
        /// 创建时间
        ///</summary>
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 更新时间
        ///</summary>
        public System.DateTime? UpdateTime { get; set; } // UpdateTime

        ///<summary>
        /// 店铺唯一编号
        ///</summary>
        public System.Guid? StoreUniqueId { get; set; } // StoreUniqueID

        ///<summary>
        /// 关键词
        ///</summary>
        public string KeyWords { get; set; } // KeyWords (length: 2000)

        public VendingMachine()
        {
            IsActivate = false;
            Currency = "RMB";
            Country = 1;
            Province = 0;
            City = 0;
            District = 0;
            Longitude = 0;
            Latitude = 0;
            IsRecommend = false;
            CreateTime = System.DateTime.Now;
            UpdateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
