// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConsoleApp
{

    // VendingMachineProduct
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class VendingMachineProductConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VendingMachineProduct>
    {
        public VendingMachineProductConfiguration()
            : this("dbo")
        {
        }

        public VendingMachineProductConfiguration(string schema)
        {
            ToTable("VendingMachineProduct", schema);
            HasKey(x => x.UniqueId);

            Property(x => x.UniqueId).HasColumnName(@"UniqueID").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.ProductUniqueId).HasColumnName(@"ProductUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.ProductName).HasColumnName(@"ProductName").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.VendingMachineUniqueId).HasColumnName(@"VendingMachineUniqueID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Line).HasColumnName(@"Line").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(32);
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsOptional();
            Property(x => x.StoreCategoryId).HasColumnName(@"StoreCategoryID").HasColumnType("bigint").IsOptional();
            Property(x => x.StoreCategoryName).HasColumnName(@"StoreCategoryName").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.UpdateTime).HasColumnName(@"UpdateTime").HasColumnType("datetime").IsOptional();
        }
    }

}
// </auto-generated>
